-- Create item_aliases table
CREATE TABLE IF NOT EXISTS item_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name TEXT NOT NULL,
    alias TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_item_aliases_alias ON item_aliases(alias);
CREATE INDEX IF NOT EXISTS idx_item_aliases_item_name ON item_aliases(item_name);
